#! /bin/sh

if [[ "$1" == "docker" ]]; then
	echo "Setting postgres env variables to use docker container"
  export PGPORT=54321
  export PGPASSWORD=$DOCKER_PGPASS
  export PGUSER=$DOCKER_PGUSER
elif [[ "$1" == "prod-read-replica" ]]; then
	echo "Setting postgres env variables to use the prod read replica"
  export PGPORT=5432
  export PGHOST=$PROD_RR_PGHOST
  export PGPASSWORD=$PROD_RR_PGPASS
  export PGUSER=$PROD_RR_PGUSER
else
	echo "Setting postgres env variables to use local install"
  source /etc/profile.d/postgres.sh
fi
