#! /bin/sh

if [[ "$1" == "docker" ]]; then
	echo "Setting postgres env variables to use docker container"
  export PGPORT=54321
  export PGPASSWORD=$DOCKER_PGUSER
  export PGUSER=$DOCKER_PGPASS
else
	echo "Setting postgres env variables to use local install"
  source /etc/profile.d/postgres.sh
fi
